sonar.projectKey=last-mile-logistics
sonar.projectName=Last-Mile Logistics
sonar.sources=services
sonar.exclusions=**/*_test.go,**/migrations/**
sonar.tests=services
sonar.test.inclusions=**/*_test.go
sonar.go.coverage.reportPaths=coverage/**/coverage.out
sonar.qualitygate.wait=true
